use std::{env, fs, path::PathBuf};

const EXPECTED_API_VERSION: u32 = 1;

fn main() {
    println!("cargo:rerun-if-changed=src/version.rs");

    let version_source =
        fs::read_to_string("src/version.rs").expect("failed to read src/version.rs");
    let api_version = parse_api_version(&version_source);

    assert_eq!(
        api_version, EXPECTED_API_VERSION,
        "API_VERSION changed; update the generated header version assertion"
    );

    let header = format!(
        "// GENERATED by wallet-node-api/build.rs — do not edit.\n\
         #ifndef WALLET_NODE_API_VERSION_H\n\
         #define WALLET_NODE_API_VERSION_H\n\
         \n\
         #define WALLET_NODE_API_VERSION {api_version}\n\
         \n\
         #endif\n"
    );

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is not set"));
    fs::write(out_dir.join("wallet_node_api_version.h"), header)
        .expect("failed to write wallet_node_api_version.h");
}

fn parse_api_version(source: &str) -> u32 {
    let line = source
        .lines()
        .find(|line| line.contains("pub const API_VERSION"))
        .expect("pub const API_VERSION not found in src/version.rs");
    let value = line
        .split('=')
        .nth(1)
        .expect("API_VERSION assignment missing")
        .trim()
        .trim_end_matches(';')
        .trim()
        .trim_end_matches("u32")
        .trim();

    value.parse().expect("API_VERSION is not an integer")
}
